var searchData=
[
  ['objectname',['objectName',['http://qt-project.org/doc/qt-5/qobject.html#objectName-prop',1,'QObject']]],
  ['offset',['offset',['http://qt-project.org/doc/qt-5/qgraphicsdropshadoweffect.html#offset-prop',1,'QGraphicsDropShadowEffect::offset()'],['http://qt-project.org/doc/qt-5/qpangesture.html#offset-prop',1,'QPanGesture::offset()']]],
  ['okbuttontext',['okButtonText',['http://qt-project.org/doc/qt-5/qinputdialog.html#okButtonText-prop',1,'QInputDialog']]],
  ['opacity',['opacity',['http://qt-project.org/doc/qt-5/qwindow.html#opacity-prop',1,'QWindow::opacity()'],['http://qt-project.org/doc/qt-5/qgraphicsopacityeffect.html#opacity-prop',1,'QGraphicsOpacityEffect::opacity()'],['http://qt-project.org/doc/qt-5/qgraphicsobject.html#opacity-prop',1,'QGraphicsObject::opacity()'],['../class_sprite.html#a13d277baaddb57974a086145ce02d44c',1,'Sprite::opacity()']]],
  ['opacitymask',['opacityMask',['http://qt-project.org/doc/qt-5/qgraphicsopacityeffect.html#opacityMask-prop',1,'QGraphicsOpacityEffect']]],
  ['opaqueresize',['opaqueResize',['http://qt-project.org/doc/qt-5/qsplitter.html#opaqueResize-prop',1,'QSplitter']]],
  ['openexternallinks',['openExternalLinks',['http://qt-project.org/doc/qt-5/qgraphicstextitem.html#openExternalLinks-prop',1,'QGraphicsTextItem::openExternalLinks()'],['http://qt-project.org/doc/qt-5/qlabel.html#openExternalLinks-prop',1,'QLabel::openExternalLinks()'],['http://qt-project.org/doc/qt-5/qtextbrowser.html#openExternalLinks-prop',1,'QTextBrowser::openExternalLinks()']]],
  ['openlinks',['openLinks',['http://qt-project.org/doc/qt-5/qtextbrowser.html#openLinks-prop',1,'QTextBrowser']]],
  ['optimizationflags',['optimizationFlags',['http://qt-project.org/doc/qt-5/qgraphicsview.html#optimizationFlags-prop',1,'QGraphicsView']]],
  ['options',['options',['http://qt-project.org/doc/qt-5/qcolordialog.html#options-prop',1,'QColorDialog::options()'],['http://qt-project.org/doc/qt-5/qfiledialog.html#options-prop',1,'QFileDialog::options()'],['http://qt-project.org/doc/qt-5/qfontdialog.html#options-prop',1,'QFontDialog::options()'],['http://qt-project.org/doc/qt-5/qinputdialog.html#options-prop',1,'QInputDialog::options()'],['http://qt-project.org/doc/qt-5/qwizard.html#options-prop',1,'QWizard::options()']]],
  ['organizationdomain',['organizationDomain',['http://qt-project.org/doc/qt-5/qcoreapplication.html#organizationDomain-prop',1,'QCoreApplication']]],
  ['organizationname',['organizationName',['http://qt-project.org/doc/qt-5/qcoreapplication.html#organizationName-prop',1,'QCoreApplication']]],
  ['orientation',['orientation',['http://qt-project.org/doc/qt-5/qscreen.html#orientation-prop',1,'QScreen::orientation()'],['http://qt-project.org/doc/qt-5/qdatawidgetmapper.html#orientation-prop',1,'QDataWidgetMapper::orientation()'],['http://qt-project.org/doc/qt-5/qabstractslider.html#orientation-prop',1,'QAbstractSlider::orientation()'],['http://qt-project.org/doc/qt-5/qdialogbuttonbox.html#orientation-prop',1,'QDialogButtonBox::orientation()'],['http://qt-project.org/doc/qt-5/qprogressbar.html#orientation-prop',1,'QProgressBar::orientation()'],['http://qt-project.org/doc/qt-5/qsplitter.html#orientation-prop',1,'QSplitter::orientation()'],['http://qt-project.org/doc/qt-5/qtoolbar.html#orientation-prop',1,'QToolBar::orientation()']]],
  ['origin',['origin',['http://qt-project.org/doc/qt-5/qgraphicsscale.html#origin-prop',1,'QGraphicsScale::origin()'],['http://qt-project.org/doc/qt-5/qgraphicsrotation.html#origin-prop',1,'QGraphicsRotation::origin()']]],
  ['overwritemode',['overwriteMode',['http://qt-project.org/doc/qt-5/qplaintextedit.html#overwriteMode-prop',1,'QPlainTextEdit::overwriteMode()'],['http://qt-project.org/doc/qt-5/qtextedit.html#overwriteMode-prop',1,'QTextEdit::overwriteMode()']]]
];
